version: '3'
services:
    redis:
        image: redis:latest
    melichalenge:
        image: melichallenge
        ports:
            - 8080:80/tcp
            - 8081:443/tcp
        depends_on:
        - redis